services:
  mongodb:
    image: mongo:latest
    container_name: interneers_lab_mongodb
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - django_app/.env
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: